### ISSUE TITLE
package description and example are wrong/outdated

### ISSUE THREAD

**Issue by vatula** [kesla/download-npm-package#15]
NPM package description gives this usage example
`
import downloadNpmPackage from 'download-npm-package';
 
downloadNpmPackage({
  arg: 'modulname@version' // for example, npm@2 or @mic/version@latest etc 
  path: '/tmp' // package will be downlodaded to ${path}/packageName 
}).then()
`

There is no "path" option. It's called "dir" in the source code. Current example fails to process the package. It works okay when path is replaced with dir.

**Comment by kesla** [comment]
Should've been fixed by #14, which now has been released to npm
